### ISSUE TITLE
Add a new format that can be more interactive/explorable

### ISSUE THREAD

**Issue by diego-ojeda-binbash** [dineshba/tf-summarize#17]
It would be an extension to the existing formats/views but instead of hiding the specific changes to the resources that Terraform plans to make, we would have the option to click on the resources and expand them in order to view those details.

**Comment by dineshba** [comment]
This PR might solve the requirement upto some extend https://github.com/dineshba/tf-summarize/pull/18

Let me know your thoughts @diego-ojeda-binbash @marianod92

**Comment by diego-ojeda-binbash** [comment]
@dineshba You're right. Sounds like that's what we want. Thanks for pointing that out and sorry for not noticing that issue before.
I can close this issue now. I will definitely vote and follow the other one.

Duplicate of #18
