### ISSUE TITLE
Question: Integrate into Terragrunt workflow

### ISSUE THREAD

**Issue by armenr** [dineshba/tf-summarize#23]
Hello and thank you for your amazing work on this project! I'm trying to figure out how to get this worked into our existing terragrunt workflow.

I might be missing something obvious...but I've had one heck of a time trying to get this to work with terragrunt.

I figured I might as well ask here, in case the maintainers have already figured that out/have a working example of that.

Thank you!
_Armen

**Comment by Mike-Nahmias** [comment]
I haven't had any issues so far:
```
terragrunt plan -out tfplan
terragrunt show -json tfplan | tf-summarize
```

**Comment by dineshba** [comment]
Hi @Mike-Nahmias, Thanks for confirming. Hope all the features like `-tree`, `-md` are working fine with terragrunt.

>I don't have the terragrunt setup with me, so I am not able to test it. 

@armenr Could you please try above commands in your terragrunt setup and let me know if we need to some code change to support terragrunt.

**Comment by dineshba** [comment]
Thanks @jnavarrof for confirming. I will close this issue @armenr. Please let me us know if you still face issue with `terragrunt + tf-summarize`
