### ISSUE TITLE
Markdown table format is not compatible with github/gitlab

### ISSUE THREAD

**Issue by stv-io** [dineshba/tf-summarize#25]
Hey all, fantastic tool, requesting a small change / improvement, to be able to integrate this in CI pipelines, and summarize the output nicely.

Currently, it seems that the markdown table is using an old markdown syntax.

```
❯ tf-summarize -out=summary.md tfplan 
Written plan summary to summary.md
```

renders the below, escaping in backticks 

**Current**

```
+--------+------------------------------------------+
| CHANGE |                   NAME                   |
+--------+------------------------------------------+
| update | module.ec2_instance.aws_instance.this[0] |
+--------+------------------------------------------+
```

In rendered markdown in github, this yields

+--------+------------------------------------------+
| CHANGE |                   NAME                   |
+--------+------------------------------------------+
| update | module.ec2_instance.aws_instance.this[0] |
+--------+------------------------------------------+

In a gitlab comment this would be

<img width="995" alt="image" src="https://user-images.githubusercontent.com/6401588/211006536-368f588f-1fd2-4781-b899-58ca6560454b.png">

This is clearly not as it should be however if it's changed to:

**Expected**

```
| CHANGE |                   NAME                   |
|--------|------------------------------------------|
| update | module.ec2_instance.aws_instance.this[0] |
```

it renders as expected

| CHANGE |                   NAME                   |
|--------|------------------------------------------|
| update | module.ec2_instance.aws_instance.this[0] |

and 

<img width="474" alt="image" src="https://user-images.githubusercontent.com/6401588/211006886-354ad729-a03a-41e2-a20c-3254eefec0b8.png">

References
 - https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables
 - https://docs.gitlab.com/ee/user/markdown.html#tables

**Comment by dineshba** [comment]
Hi @stv-io, Thanks for trying out the tool.

For markdown output, you have to add `-md` flag

```sh
❯ tf-summarize -md -out=summary.md tfplan 
```

Please try it and let us know if you have any issue with the output

**Comment by stv-io** [comment]
sorry, seems like I should have RTFM'd, indeed it works, thank you 🙇🏼 

```console
❯ tf-summarize -md -out=summary.md tfplan
Written plan summary to summary.md

tf-project-example/shared
❯ cat summary.md
| CHANGE |                    NAME                    |
|--------|--------------------------------------------|
| update | `module.ec2_instance.aws_instance.this[0]` |
```

| CHANGE |                    NAME                    |
|--------|--------------------------------------------|
| update | `module.ec2_instance.aws_instance.this[0]` |
