### ISSUE TITLE
Fix asdf installation method

### ISSUE THREAD

**Issue by tomas-balaz** [dineshba/tf-summarize#27]
command `asdf plugin install tf-summarize` you provided in the [docs](https://github.com/dineshba/tf-summarize/blob/6a52b0b33ff224d2292d9eb6d0208e94ee1f5f0e/README.md?plain=1#L54) leads to the error
```
$  asdf plugin install tf-summarize

Unknown command: `asdf plugin install tf-summarize`
No plugin named plugin
```

the right command which works is `asdf plugin add tf-summarize`

please fix it in the README

**Comment by dineshba** [comment]
Thanks for reporting the issue @tomas-balaz ... Updated the readme.
