### ISSUE TITLE
Add recreate section

### ISSUE THREAD

**Issue by nitrocode** [dineshba/tf-summarize#3]
Very cool command line utility.

I'd love to see a new section called `recreate` to see which resources are going to be both added and deleted with the same arguments/configuration.

**Comment by dineshba** [comment]
It was already added. I forgot to release it in brew.

Updated the brew now. Please use version `0.2.2` now.

Sample output: In below example `null_resource.test` is recreate

![image](https://user-images.githubusercontent.com/13361187/194103195-8491f1d1-d01e-4da3-adfc-78ab9ef3557b.png)

**Comment by dineshba** [comment]
I am closing this as this is fixed in latest release. Please let me know if we have to reopen this.
