### ISSUE TITLE
notation (-/+) and (+/-)

### ISSUE THREAD

**Issue by millouzgc** [dineshba/tf-summarize#42]
Hello, the differentiation between the notation (-/+) and (+/-) is missing.

https://github.com/dineshba/tf-summarize/blob/c091e4e111dd8e7d16c2f920645c33e032c39e81/terraformstate/terraform_state.go#L50C1-L51C19

**Comment by dineshba** [comment]
Sure, we can change it to `(-/+)`

**Comment by dineshba** [comment]
Sure, let me try to find the logic to do that. Feel free to create a PR also

**Comment by dineshba** [comment]
Closing this with https://github.com/dineshba/tf-summarize/pull/59
