### ISSUE TITLE
Support "import" as a first class change type for people using terraform 1.5+

### ISSUE THREAD

**Issue by kishaningithub** [dineshba/tf-summarize#47]
Terraform 1.5 made import a first class citizen. Links below

- https://developer.hashicorp.com/terraform/language/import
- https://www.virtualizationhowto.com/2023/07/terraform-import-existing-resource-ultimate-guide/ 

As of now, even though `terraform plan` command shows something like the following(note the no. of imports) but this tool does not show the list of import changes that are going to be applied

```
Plan: 22 to import, 0 to add, 6 to change, 0 to destroy.
```

**Comment by dineshba** [comment]
Fix has been merged and release. Can we close this issue @kishaningithub  ?

**Comment by kishaningithub** [comment]
Yes we can 👍😊
