### ISSUE TITLE
Refactor to use terraform-json package

### ISSUE THREAD

**Issue by kishaningithub** [dineshba/tf-summarize#48]
[From what i see](https://github.com/dineshba/tf-summarize/blob/c308ae3a61db8d6e869bdc82729c5e858326d00b/terraformstate/terraform_state.go#L16) this tool reads the terraform's standard output format. To enable future compatibility and simplify the codebase i recommend using the following package provided by hashicorp to read the common json format

https://github.com/hashicorp/terraform-json

What are your views on this?

**Comment by dineshba** [comment]
I agree with using this https://github.com/hashicorp/terraform-json. It will be very helpful. Thanks for this input @kishaningithub

**Comment by QuintenBruynseraede** [comment]
Hi @dineshba you can assign this to me if still relevant

**Comment by kishaningithub** [comment]
Also @QuintenBruynseraede Feel free to create a draft PR and reach out for help if needed :-)

**Comment by QuintenBruynseraede** [comment]
Hey @dineshba patiently waiting for you input on this (large) PR. Lmk if I can do anything
