### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by cillierscharl** [dineshba/tf-summarize#49]
Hi there,

Some of the newest commits are super helpful (for example omitting the second table output if its empty), is there a timeline on releasing a new version?

**Comment by cillierscharl** [comment]
@dineshba @kishaningithub Any thoughts on how this repo progresses or is it stale?

Cheers

**Comment by kishaningithub** [comment]
@cillierscharl As of now I am only a contributor of this repo and not a maintainer as such.

**Comment by dineshba** [comment]
Thanks @cillierscharl for checking. I missed to make a release this time.

Just release a new version [v0.3.3](https://github.com/dineshba/tf-summarize/releases).

Will think about auto release when new commits merged to main branch.
