### ISSUE TITLE
Is there some Github Actions to setup tf-summarize?

### ISSUE THREAD

**Issue by landradetractian** [dineshba/tf-summarize#5]
Does anyone know it? I could work in that if doesn't exist yet.

**Comment by dineshba** [comment]
As far as I know, it doesn't exist. It would be great if you could contribute on that. Thank you.

**Comment by dineshba** [comment]
Until we create a new github action for tf-summarize, we can use small script to install it. Details https://github.com/dineshba/tf-summarize#github-actions-workflow

**Comment by kishaningithub** [comment]
I have just created one @landradetractian @dineshba :-)

https://github.com/kishaningithub/setup-tf-summarize
