### ISSUE TITLE
Add A Machine Readable Output Option

### ISSUE THREAD

**Issue by fergoid** [dineshba/tf-summarize#53]
I love this utility and use it all the time. I would like the option of an unformatted / machine readable format. Maybe something like CSV or JSON. 
My use case is to parse the output and create a list of IAM permissions based on it  that could be used in a role to support the  Terraform on AWS.

**Comment by dineshba** [comment]
Thanks for your feedback 👍🏽 

Will this be helpful ? `tf-summarize -json tfplan`

**Comment by fergoid** [comment]
> Thanks for your feedback 👍🏽
> 
> Will this be helpful ? `tf-summarize -json tfplan`

Looks good, happy to try and create the PR if you like?

**Comment by dineshba** [comment]
It is already available. Can you try it and let see if the expected feature is already there.

**Comment by fergoid** [comment]
thanks it isn't quite what i needed so we can close this now

**Comment by dineshba** [comment]
Okay sure. Thanks for the update
